export { default as Home } from './Home.jsx';
export { default as Orders } from './Orders.jsx';
export { default as Menu } from './Menu.jsx';
export { default as AboutUs } from './AboutUs.jsx';
export { default as Booking } from './Booking.jsx';
export { default as Invoice } from './Invoice.jsx';
export { default as PaymentResult } from './PaymentResult.jsx';
export { default as StaffHome } from './StaffHome.jsx';
export { default as CustomerLanding } from './CustomerLanding.jsx';
